// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmJCssr5k2Lm4uAfSxegXEAQnq4OKzg50',
    appId: '1:83903925512:android:548d0e40fd399a3f7bb0bd',
    messagingSenderId: '83903925512',
    projectId: 'my-boat-a9c54',
    databaseURL: 'https://my-boat-a9c54-default-rtdb.firebaseio.com',
    storageBucket: 'my-boat-a9c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLcebXdT_4pOoUPRR9k0BEKS76EZ6PSA',
    appId: '1:83903925512:ios:e0267e5b465f561c7bb0bd',
    messagingSenderId: '83903925512',
    projectId: 'my-boat-a9c54',
    databaseURL: 'https://my-boat-a9c54-default-rtdb.firebaseio.com',
    storageBucket: 'my-boat-a9c54.firebasestorage.app',
    androidClientId: '83903925512-7d1i3mbg3k6fdkjc48jdj2d7uscr8kke.apps.googleusercontent.com',
    iosClientId: '83903925512-3c3ct8tr2e8b2pv8ecc9582s4amufdfi.apps.googleusercontent.com',
    iosBundleId: 'com.app.boatappowner',
  );
}
